import { promises as fs } from "node:fs";
import path from "node:path";

type MonsterPrompt = {
  id: string;
  name: string;
  size: string;
  type: string;
  framing: "headshot" | "bust" | "full";
  style: {
    artStyle: string;
    lighting: string;
    palette?: string[];
  };
  prompt: string;
  negativePrompt?: string;
  seed?: number;
  variants?: number;
  output?: {
    portrait?: { width?: number; height?: number; format?: "png" | "webp" };
    token?: { size?: number; format?: "png" | "webp" };
  };
  notes?: string;
};

type ManifestItem = {
  itemId: string;
  promptId: string;
  variant: number;
  status: "pending" | "generated" | "failed";
  outputs: {
    portrait: { filename: string; format: "png" | "webp" };
    token: { filename: string; format: "png" | "webp" };
  };
};

type GenerationManifest = {
  manifestId: string;
  createdAt: string;
  provider: string;
  notes?: string;
  items: ManifestItem[];
};

const defaultInput = "tools/art-generator/data/monster-prompts.json";
const defaultOut = "tools/art-generator/output/manifests/portrait-manifest.json";
const defaultProvider = "local";

const args = new Map(
  process.argv
    .slice(2)
    .map((arg, index, all) => (arg.startsWith("--") ? [arg, all[index + 1]] : null))
    .filter(Boolean) as Array<[string, string]>
);

const inputPath = args.get("--input") ?? defaultInput;
const outPath = args.get("--out") ?? defaultOut;
const provider = args.get("--provider") ?? defaultProvider;

const normalizeFormat = (value: unknown, fallback: "png" | "webp"): "png" | "webp" => {
  return value === "webp" ? "webp" : fallback;
};

const buildItemId = (promptId: string, variant: number) => {
  return variant === 1 ? promptId : `${promptId}-v${variant}`;
};

const loadPrompts = async (filePath: string): Promise<MonsterPrompt[]> => {
  const raw = await fs.readFile(filePath, "utf8");
  const data = JSON.parse(raw) as unknown;
  if (!Array.isArray(data)) {
    throw new Error("Prompt file must be a JSON array");
  }
  return data as MonsterPrompt[];
};

const ensureDir = async (filePath: string) => {
  const dir = path.dirname(filePath);
  await fs.mkdir(dir, { recursive: true });
};

const main = async () => {
  const prompts = await loadPrompts(inputPath);
  const items: ManifestItem[] = [];

  for (const prompt of prompts) {
    if (!prompt?.id || !prompt?.name) {
      throw new Error(`Prompt missing id or name: ${JSON.stringify(prompt)}`);
    }
    const variants = Math.max(1, prompt.variants ?? 1);
    const portraitFormat = normalizeFormat(prompt.output?.portrait?.format, "png");
    const tokenFormat = normalizeFormat(prompt.output?.token?.format, "png");

    for (let variant = 1; variant <= variants; variant += 1) {
      const itemId = buildItemId(prompt.id, variant);
      items.push({
        itemId,
        promptId: prompt.id,
        variant,
        status: "pending",
        outputs: {
          portrait: {
            filename: `${itemId}.${portraitFormat}`,
            format: portraitFormat
          },
          token: {
            filename: `${itemId}-token.${tokenFormat}`,
            format: tokenFormat
          }
        }
      });
    }
  }

  const manifest: GenerationManifest = {
    manifestId: `portrait-${Date.now()}`,
    createdAt: new Date().toISOString(),
    provider,
    notes: "Generated by tools/art-generator/scripts/generate-manifest.ts",
    items
  };

  await ensureDir(outPath);
  await fs.writeFile(outPath, JSON.stringify(manifest, null, 2));

  const relativeOut = path.relative(process.cwd(), outPath);
  process.stdout.write(`Wrote ${relativeOut}\n`);
};

main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exit(1);
});
